# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoinCalculator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoinCalculator
  pod 'Alamofire', '~> 4.5'
  pod 'PubNub', '~> 4'

  target 'CoinCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinCalculatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
