# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'CoinCalculator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoinCalculator
  pod 'Alamofire', '~> 4.5'
  pod 'PubNub', '~> 4'
  pod 'Charts'

  target 'CoinCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoinCalculatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do | installer |
  require 'fileutils'

  FileUtils.cp_r('Pods/Target Support Files/Pods-CoinCalculator/Pods-CoinCalculator-acknowledgements.plist', 'CoinCalculator/Supporting Files/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

end